export * from './queries/Students'
export * from './queries/StudentDetails'
export * from './queries/AllCourses'
export * from './mutations/RegisterCourse'
export * from './mutations/Login'
export * from './mutations/Logout'